@HostAddress = https://localhost:7111

### Register a new customer
POST {{HostAddress}}/api/customers/register
Content-Type: application/json

{
  "fullName": "Rijan Test",
  "email": "rijan.test@example.com",
  "phoneNumber": "9800000000",
  "address": "Kathmandu, Nepal",
  "password": "TestPass123!",
  "confirmPassword": "TestPass123!"
}