// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleInventoryManagementSystem.Infrastructure.Presistance;

#nullable disable

namespace VehicleInventoryManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520065111_AddAlertsTable")]
    partial class AddAlertsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Admin", b =>
                {
                    b.Property<int>("Admin_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Admin_ID"));

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Admin_ID");

                    b.HasIndex("User_Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Appointment", b =>
                {
                    b.Property<int>("Appointment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Appointment_ID"));

                    b.Property<DateTime>("Appointment_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Appointment_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Service_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Vehicle_ID")
                        .HasColumnType("integer");

                    b.HasKey("Appointment_ID");

                    b.HasIndex("Vehicle_ID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Customer", b =>
                {
                    b.Property<int>("Customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Customer_ID"));

                    b.Property<DateTime?>("Credit_Due_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Pending_Credit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total_Spent")
                        .HasColumnType("numeric");

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Customer_ID");

                    b.HasIndex("User_Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.PartRequest", b =>
                {
                    b.Property<int>("Request_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Request_ID"));

                    b.Property<int>("Customer_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Request_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Requested_Part_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Requested_Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Request_ID");

                    b.HasIndex("Customer_ID");

                    b.ToTable("PartRequests");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Purchase_Invoice_No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Purchase_Invoice_No"));

                    b.Property<int>("Admin_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Invoice_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Purchase_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tax_Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total_Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("Vendor_ID")
                        .HasColumnType("integer");

                    b.HasKey("Purchase_Invoice_No");

                    b.HasIndex("Admin_ID");

                    b.HasIndex("Vendor_ID");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.PurchaseItem", b =>
                {
                    b.Property<int>("Purchase_Invoice_No")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("Part_ID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Line_Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Purchase_Unit_Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity_Purchased")
                        .HasColumnType("integer");

                    b.HasKey("Purchase_Invoice_No", "Part_ID");

                    b.HasIndex("Part_ID");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Review", b =>
                {
                    b.Property<int>("Review_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Review_ID"));

                    b.Property<int>("Appointment_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Review_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Review_ID");

                    b.HasIndex("Appointment_ID")
                        .IsUnique();

                    b.HasIndex("Customer_ID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "e3c4b406-ae78-4216-a12f-9c82e0449831",
                            Description = "Full System Access",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "e3c4b406-ae78-4216-a12f-9c82e0449832",
                            Description = "Inventory & Sales Management",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "e3c4b406-ae78-4216-a12f-9c82e0449833",
                            Description = "Vehicle Owner",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Sales_Invoice_No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sales_Invoice_No"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Credit_Due_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Discount_Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Final_Total")
                        .HasColumnType("numeric");

                    b.Property<bool>("Is_Paid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Sales_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Staff_ID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("numeric");

                    b.HasKey("Sales_Invoice_No");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Staff_ID");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.SalesItem", b =>
                {
                    b.Property<int>("Sales_Invoice_No")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("Part_ID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Quantity_Sold")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total_Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("numeric");

                    b.HasKey("Sales_Invoice_No", "Part_ID");

                    b.HasIndex("Part_ID");

                    b.ToTable("SalesItems");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Staff", b =>
                {
                    b.Property<int>("Staff_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Staff_ID"));

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Staff_ID");

                    b.HasIndex("User_Id");

                    b.ToTable("StaffProfiles");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("Vehicle_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Vehicle_ID"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Fuel_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Manufacture_Year")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reg_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usage_Pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vehicle_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Vehicle_ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Reg_Number")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.VehiclePart", b =>
                {
                    b.Property<int>("Part_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Part_ID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("Minimum_Stock_Level")
                        .HasColumnType("integer");

                    b.Property<string>("Part_Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Part_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Purchase_Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock_Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Part_ID");

                    b.ToTable("VehicleParts");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Vendor", b =>
                {
                    b.Property<int>("Vendor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Vendor_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor_Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vendor_Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vendor_Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vendor_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Vendor_ID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Admin", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Alert", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.VehiclePart", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Appointment", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("Vehicle_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Customer", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.PartRequest", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("Admin_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("Vendor_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.PurchaseItem", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.VehiclePart", "VehiclePart")
                        .WithMany()
                        .HasForeignKey("Part_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("Purchase_Invoice_No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("VehiclePart");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Review", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("Appointment_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.SalesInvoice", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("Staff_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.SalesItem", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.VehiclePart", "VehiclePart")
                        .WithMany()
                        .HasForeignKey("Part_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.SalesInvoice", "SalesInvoice")
                        .WithMany()
                        .HasForeignKey("Sales_Invoice_No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesInvoice");

                    b.Navigation("VehiclePart");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Staff", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleInventoryManagementSystem.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehicleInventoryManagementSystem.Domain.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("PurchaseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
